spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/lite_shop?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2633792
    xa:
      properties:
        userInformationSchema: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    password: 2633
    port: 6379
    host: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /lite_shop
    listener:
      simple:
      #手动确认
        acknowledge-mode: manual
localDate:
  date-format: "yyyy-MM-dd"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0




logging:
  level:
    com.ohayou.liteshop.dao: debug

qiniu:
  accesskey: bNiSCBezONeIP9QxeDNMeAHPJAYrWmki925F2BLp
  secretKey: CWCbnnukD05mhiAgiL54wJmN9Rz_Hi-mJj_3VomQ
  bucketName: liteshopcool2
  fileDomain: http://qii5ng5sw.hb-bkt.clouddn.com

kdniao:
  EBusinessID: 1674459
  AppKey: 60738b04-cd7d-4424-915e-0cc794da9fef
  ReqURL: http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60*24)
  refresh_time: 900
  tokenHead: Bearer  #JWT负载中拿到开头

keyPrefix:
  expireTime:
    invalidToken: 900

admin:
  base_url: /api/admin
  initialPassword : 123456

portal:
  sessionExpireTime : 604800 #前台用户session过期时间

